3.0 - correct path in missing_layout suggestions
wrong (please note Layout/ missing part and L character before docs.ctp):
```php
Missing Layout
Error: The layout file Ldocs.ctp can not be found or does not exist.

Confirm you have created the file: Ldocs.ctp	in one of the following paths:

[..]/src/Template/Plugin/Oven/Ldocs.ctp
[..]/plugins/Oven/src/Template/Ldocs.ctp
[..]/src/Template/Ldocs.ctp
```

correct:

```php
Missing Layout
Error: The layout file Layout/docs.ctp can not be found or does not exist.

Confirm you have created the file: Layout/docs.ctp	in one of the following paths:

[..]/src/Template/Plugin/Oven/Layout/docs.ctp
[..]/plugins/Oven/src/Template/Layout/docs.ctp
[..]/src/Template/Layout/docs.ctp
```